### ISSUE TITLE
Indentation problems with the yang output format

### ISSUE THREAD

**Issue by wlupton** [mbj4668/pyang#616]
There seem to be several indentation-related problems with the yang output format. I suspect (but am not certain) that some of them are relatively recent.
1. child statement can be indented too much if parent statement has a multi-line argument
2. 'when' arguments can be wrapped to multiple lines without leading spaces (probably this affects all statements that prefer single-quote args?)
3. child statement can be indented too much if parent statement has a multi-line argument (take 2: the probable fix for take 1 doesn't fix this, so I think a different code path is involved)

I think I see how to fix case 1 (I think that `emit_arg()` (`else` case) should return `need_nl` rather than `True`) but haven't yet looked into fixes for the other two. 

The three cases are illustrated by the YANG shown below, and the output when running this command:
```
% pyang --format=yang --yang-line-length=70 indent-bug.yang
```

INPUT
```
module indent-bug {
  namespace "urn:indent-bug";
  prefix indent-bug;

  container case1 {
    description
      "emit-arg for multiline arguments always returns arg_on_new_line =
       True for multi-line arguments. It should return need_nl?";

    container good {
      must "'true'" {
        error-message
          "This is indented correctly.";
      }
    }

    container bad {
      must "'true' and
            'true'" {
        error-message
          "This is indented too much.";
      }
    }
  }

  container case2 {
    description
      "Single quotes are preferred for 'when' arguments, but this causes
       problems with double-quoted multi-line arguments. Should preserve the
       double quotes in this case?";

    container good {
      when "boolean(.) and boolean(.)" {
        description
          "The 'when' arg loses its double quotes but is indented correctly.";
      }
    }

    container bad {
      when "boolean(.) and
            boolean(.)" {
        description
          "The 'when' arg loses its double quotes and wraps to the start
           of the line.";
      }
    }
  }

  container case3 {
    description
      "Similar to the previous case but triggers too much indentation when
       the argument has to be split over multiple lines.";

    container good {
      when "boolean(.) and boolean(.) and boolean(.) and boolean(.)" {
        description
          "The 'when' arg loses its double quotes but is indented correctly.";
      }
    }

    container bad {
      when "boolean(.) and boolean(.) and boolean(.) and boolean(.) and
            boolean(.)" {
        description
          "The 'description' can be indented too much with
           --yang-line-length.";
      }
    }
  }
}
```

OUTPUT
```
module indent-bug {
  namespace "urn:indent-bug";
  prefix indent-bug;

  container case1 {
    description
      "emit-arg for multiline arguments always returns arg_on_new_line =
       True for multi-line arguments. It should return need_nl?";
    container good {
      must "'true'" {
        error-message "This is indented correctly.";
      }
    }
    container bad {
      must "'true' and
            'true'" {
          error-message "This is indented too much.";
      }
    }
  }
  container case2 {
    description
      "Single quotes are preferred for 'when' arguments, but this causes
       problems with double-quoted multi-line arguments. Should preserve the
       double quotes in this case?";
    container good {
      when 'boolean(.) and boolean(.)' {
        description
          "The 'when' arg loses its double quotes but is indented correctly.";
      }
    }
    container bad {
      when 'boolean(.) and
boolean(.)' {
        description
          "The 'when' arg loses its double quotes and wraps to the start
           of the line.";
      }
    }
  }
  container case3 {
    description
      "Similar to the previous case but triggers too much indentation when
       the argument has to be split over multiple lines.";
    container good {
      when 'boolean(.) and boolean(.) and boolean(.) and boolean(.)' {
        description
          "The 'when' arg loses its double quotes but is indented correctly.";
      }
    }
    container bad {
      when
        'boolean(.) and boolean(.) and boolean(.) and boolean(.) and
boolean(.)' {
          description
            "The 'description' can be indented too much with
             --yang-line-length.";
      }
    }
  }
}
```

**Comment by fredgan** [comment]
Hi William @wlupton 
I find the extra indentation are caused by the following, and the commit is b7096eca
https://github.com/mbj4668/pyang/blob/10d5ec8dad6fec047edf5586676efac66557962a/pyang/translators/yang.py#L257-L259

I am not sure why an extra indent is needed, but it seems it is added on purpose. So, I think I need Martin for some explanation. @mbj4668

**Comment by wlupton** [comment]
Thanks @fredgan. Yes that looks to be the reason for the extra indentation. Note that my suggested fix for `case1` would fix a case where I believe that `arg_on_new_line` is getting wrongly set to `True`.

I think that extra indentation is fine if it makes things look better, but I don't think that it should interfere with the rule that each additional statement level should be indented by two spaces relative to its parent. Apart from anything else, this goes against the assumptions made by the emacs yang mode!

I think all both of these (these are `case1` and `case3`) break the above rule.
```
      must "'true' and
            'true'" {
          error-message "This is indented too much.";
```
```
      when
        'boolean(.) and boolean(.) and boolean(.) and boolean(.) and
boolean(.)' {
          description
            "The 'description' can be indented too much with
             --yang-line-length.";
```

**Comment by wlupton** [comment]
I should make it clear that this is a real problem for us, because we use the `edit` transform with the `yang` format to prepare all BBF (Broadband Forum) YANG for publication. This extra indentation can result in line length warnings.

**Comment by mbj4668** [comment]
I think these are fixed in bug/i616.  Please check that it works for you.

The extra indent was a side effect from this special case:

                some-keyword
                  "arg-on-new-line" {
                    some-other-keyword
                  ^^ <- extra indentation here

But I think this was a mistake.  It is now printed as:

                some-keyword
                  "arg-on-new-line" {
                  some-other-keyword

**Comment by wlupton** [comment]
Thanks @mbj4668. I checked this in the `bug/i616` branch, and now see this:

`case1`:
* indentation is still wrong; what do you think about my suggested fix for this: `emit_arg()` (`else` case) should return `need_nl` rather than `True`
* separate question: why is the `error-message` argument on the same line? I thought that arguments of "long" keywords were put on the next line (I'll add a separate comment on this)
```
      must "'true' and
            'true'" {
          error-message "This is indented too much.";
```

`case2`:
* `when` argument has lost its double quotes and has wrapped to the start of the line
* can double quotes always be retained? did this change? if they can be retained, then the YANG author can craft multi-line `must` / `when` / `pattern` / etc. arguments secure in the knowledge that line breaks, indentation etc. will be retained
```
      when 'boolean(.) and
boolean(.)' {
        description
          "The 'when' arg loses its double quotes and wraps to the start
           of the line.";
      }
```

`case3`:
* indent fixed! thanks
```
      when
        'boolean(.) and boolean(.) and boolean(.) and boolean(.) and
boolean(.)' {
          description
            "The 'description' can be indented too much with
             --yang-line-length.";
      }
```

**Comment by mbj4668** [comment]
Are you sure you're running the code in the branch bug/i616?  All these works for me on that branch.

**Comment by wlupton** [comment]
I am so sorry! I completely forgot that I have a `pyang` alias (which uses my currently-selected default pyang), so, even though `which pyang` showed the correct binary, `pyang` used the alias.

I confirm that the bug/i616 branch fixes all the problems.

I confirm
